from math import ceil
import numpy as np
import casadi as ca
import pytest
from pathlib import Path
from rpp_py.context import ComponentContext
from rpp_py.data_manager import DataManager
from rpp_py.parameter_handler import ParameterHandler
DataManager() # hack to ensure that autogenerated files are sourced
from more_dynamics.plugins.casadi_helpers import RppCasadiGraph
from more_dynamics.simulation import simulate

STORE_DATA = True

if STORE_DATA:
    import matplotlib.pyplot as plt

@pytest.fixture
def data_manager():
    return DataManager()


def out_data_folder():
    out_dir = Path(__file__).parent / "data"
    if STORE_DATA:
        if not out_dir.exists():
            out_dir.mkdir(parents=True)
    return out_dir

def generate_steps(sim_time, dt, out_dim, steps, dim):

    n_k = ceil(sim_time / dt)

    n_steps = len(steps)
    duration = ceil(n_k / n_steps)

    ref_x = np.zeros((n_steps * duration, out_dim))

    n_k = len(ref_x)

    for i in range(n_steps):
        b = i * duration
        ref_x[b:b+duration, dim] = steps[i] * np.ones(duration)

    # time = np.linspace(0, n_k-1, n_k) * dt

    # return np.hstack((time.reshape(-1, 1), ref_x))
    return ca.DM(ref_x)


def test_jet_nozzle(data_manager: DataManager):
    from more_dynamics.plugins.jet_nozzle import JetNozzle

    # Create an instance of the JetNozzle class
    jet_nozzle = JetNozzle()
    params = ParameterHandler.resolve_params(jet_nozzle.PARAMETERS, {})
    params.params["thrust_coefficient"] = 1000.0
    params.params["thrust_rise_time"] = 0.5
    params.params["thrust_fall_time"] = 0.1
    params.params["nozzle_velocity_radpersec"] = 0.8
    params.params["min_angle"] = -0.5
    params.params["max_angle"] = 0.5
    params.params["location"] = [-1.0, 0.05, 0.1]
    params.params["trim_angle"] = 0.05
    context = ComponentContext(instance=jet_nozzle, params=params)
    context.initialize()

    graph = RppCasadiGraph(jet_nozzle.graph())

    thrust_steps = [0.5, 0.9, 0.0, 0.2] * 3
    angle_steps = [0.0, 0.5, -0.5, 0.0]

    t_sim = 30
    dt = 0.1

    inputs = generate_steps(t_sim, dt, out_dim=2, steps=thrust_steps,dim=0) \
        + generate_steps(t_sim, dt, out_dim=2, steps=angle_steps, dim=1)

    result = simulate(graph, inputs, dt, num_steps=inputs.shape[0])

    if STORE_DATA:
        time = result.time
        plt.figure()
        plt.subplot(2, 1, 1)
        plt.plot(time, result.states[:, 0], label="Thrust")
        plt.plot(time[:-1], inputs[:, 0], label="Thrust Ref", linestyle="--")
        plt.legend()
        plt.subplot(2, 1, 2)
        plt.plot(time, result.states[:, 1], label="Nozzle Angle")
        plt.plot(time[:-1], inputs[:, 1], label="Nozzle Angle Ref", linestyle="--")
        plt.legend()

        data_folder = out_data_folder()
        plt.savefig(data_folder / "jet_nozzle_states.png")

        plt.figure()
        plt.subplot(2, 1, 1)
        plt.plot(time, result.outputs[:, 0:3], label=["Force X", "Force Y", "Force Z"])
        plt.plot(time, result.states[:, 1]*1000, label="Angle", linestyle="--")
        plt.legend()
        plt.subplot(2, 1, 2)
        plt.plot(time, result.outputs[:, 3:6], label=["Torque X", "Torque Y", "Torque Z"])
        plt.plot(time, result.states[:, 1]*500, label="Angle", linestyle="--")
        plt.legend()

        plt.savefig(data_folder / "jet_nozzle_outputs.png")





